version: "3.5"
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bgt56yhNM
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql
    restart: always
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Bgt56yhNM
      MYSQL_DATABASE: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Bgt56yhNM
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - ./mongo-data:/data/db
